packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@parcel/watcher': true
  '@reown/appkit': true
  bufferutil: true
  esbuild: true
  msw: true
  unrs-resolver: true
  utf-8-validate: true
minimumReleaseAge: 20160 # If you remove or change this, you will be fired
minimumReleaseAgeExclude:
- '@0xsequence/*'
- '@0xtrails/*'
- '0xtrails'
- '0xsequence'
